config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  match '/auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  
  get '/home', to: 'static_pages#home', as: :home
  get '/about', to: 'static_pages#about', as: :about
  get '/random', to: 'posts#random', as: :random
  post '/report', to: 'reports#create', as: :report
  get '/admin', to: 'static_pages#admin', as: :admin

  resources :posts do
    member do
      put "like" , to: "posts#upvote"
      put "dislike" , to: "posts#downvote"
      get "comments" , to: "comments#show"
    end
  end

  resources :comments
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]
  resources :users, only: [:show]
  resources :tags, only: [:show]
  
  root 'posts#index'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :validate_admin!, only: [:admin]

  def home
  end

  def about
  end

  def admin
    @reported_posts = Post.where("reports_count > 0").order(reports_count: :desc).limit(15)
    @reported_comments = Comment.where("reports_count > 0").order(reports_count: :desc).limit(15)
    @most_posts = User.joins(:posts).group('users.id').order('count(posts.id) desc').limit(10)
  end

  private

    def validate_admin!
      unless current_user and current_user.admin?
        flash[:danger] = "You are not admin!"
        redirect_to root_path and return
      end
      true
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<h1>Admin Panel</h1>

<body class="admin">
<div id="exTab1" class="container pull-center"> 
  <ul  class="nav nav-pills tab_remember text-center">
    <li class="active pull-center">
      <a  href="#reported_posts" data-toggle="tab">reported posts</a>
    </li>
    <li><a href="#reported_comments" data-toggle="tab">reported comments</a>
    </li>
    <li><a href="#most_submits" data-toggle="tab">users who submit the most posts</a>
    </li>
  </ul>

  <div class="tab-content clearfix">
    
    <div class="tab-pane active" id="reported_posts">
      <h2 class="text-center">reported posts</h2>
        <% @reported_posts.each do |post| %>
          <div><%= link_to "#{post.title} - #{pluralize(post.reports_count, 'report')}", post_path(post) %></div>
        <% end %>
    </div>


    <div class="tab-pane" id="reported_comments">
      <h2 class="text-center">reported comments</h2>
        <% @reported_comments.each do |comment| %>
          <h4><%= pluralize(comment.reports_count, "report") %>:</h4>
          <div class="well">
          <%= render 'comments/comment_content', comment: comment %><br><br>
          </div>
        <% end %>
    </div>

      <div class="tab-pane text-center" id="most_submits">
      <h2>most posts</h2>

      <% count_hash = @most_posts.count %>
      <ul>
      <% @most_posts.each do |user| %>
        <li><%= link_to user.username, user_path(user) %> has <%= pluralize(count_hash[user.id], "post") %></li>
      <% end %>
      </ul>
    </div>
  </div>
  </div>
</body>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>