config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  match '/auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  
  get '/home', to: 'static_pages#home', as: :home
  get '/about', to: 'static_pages#about', as: :about
  get '/random', to: 'posts#random', as: :random
  post '/report', to: 'reports#create', as: :report
  get '/admin', to: 'static_pages#admin', as: :admin

  resources :posts do
    member do
      put "like" , to: "posts#upvote"
      put "dislike" , to: "posts#downvote"
      get "comments" , to: "comments#show"
    end
  end

  resources :comments
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]
  resources :users, only: [:show]
  resources :tags, only: [:show]
  
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user
  has_many :reports, as: :reportable

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def show
    @post = Post.find(params[:id])
    @comments = @post.root_comments
  end

  def create
    post = Post.find(comment_params[:commentable_id])
    parent_post = Comment.find(comment_params[:parent_id]) if comment_params[:parent_id].present?
    user_id = current_user.id
    comment = Comment.build_from(post,user_id,comment_params[:body])
    if comment.save
      comment.move_to_child_of(parent_post) if parent_post
      flash[:success] = "comment created."
      redirect_to comments_post_path(post) and return
    else
      flash[:error] = "#{comment.errors.full_messages}"
      redirect_to :back and return
    end
  end

  def update
    @comment = Comment.find(params[:id])
    redirect_to :back if @comment.user != current_user

    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.html { redirect_to(@comment, :notice => 'comment was successfully updated.') }
        # Handles BIP attributes (everything but attachment)
        format.json { respond_with_bip(@comment) }
        # Handles attachment
        format.js
      else
        format.html { render :action => "edit" }
        # Handles BIP attributes (everything but attachment)
        format.json { respond_with_bip(@comment) }
        # Handles attachment
        format.js
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy if comment.user = current_user
    flash[:succes] = "comment deleted."
    redirect_to :back
  end

  private

    def comment_params
      params.require(:comment).permit(:body, :commentable_id, :commentable_type,
                                      :parent_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="well">
  <%= render "comments/comment_content", comment: comment %>

  <% if current_user %>
    <button class="btn btn-default sharp pull-right reply_button">reply</button>
  <% end %>

</div>

<% if current_user %>
  <div class="reply_form"><%= render 'comments/comment_form', parent_id: comment.id %></div>
<% end %>  

<% comment.children.each do |comment| %>
    <div class="well child_comment">
      <%= render "comments/comment_content", comment: comment %>
    </div>
<% end %>

app/views/comments/_comment_content.html.erb
<%= render 'shared/written_content_header', user: comment.user, item: comment %>

<div class="message_content"><%= best_in_place_if comment.user == current_user, comment, :body, as: :textarea, activator: "#edit_comment_#{comment.id}" %>
</div>

<% if current_user %>
  <ul class="text-left comment_options">
    <li><%= link_to "report", report_path(report: {reportable_id: comment.id, reportable_type: "Comment"}), id: "report_#{comment.class}_#{comment.id}", class: "report_link", remote: true, method: :post %></li>
  <% if current_user == comment.user || (current_user and current_user.admin?) %> 
  
    <li>| <%= link_to 'edit', "#", id: "edit_comment_#{comment.id}" %></li>
    <li>| <%= link_to 'delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  
  <%end%>
  </ul>
<% end %>   

app/views/comments/_comment_form.html.erb
<% parent_id = nil if local_assigns[:parent_id].nil? %>

<%= form_for Comment.new do |f| %>
  <div class="row">
    <div class="col-md-5">
      <%= f.hidden_field :parent_id, value: parent_id %>
      <%= f.hidden_field :commentable_id, value: @post.id %>
      <%= f.hidden_field :commentable_type, value: @post.class.to_s %>
      <%= f.text_area :body, placeholder: "submit a comment", class: "form-control form-control-gray" %>
    </div>
    <div class="col-md-3">
      <%= f.submit "Save", class: "btn btn-default sharp" %>
    </div>
  </div>  
<% end %>

app/views/comments/show.html.erb
<h2 class="show_page_title">comments for "<%= @post.title %>"</h2>

<p id="notice"><%= notice %></p>

<%= render "posts/post", post: @post, small: true %>

<%= link_to 'Back', posts_path %>

<%= render 'comments/comment_form' if current_user %>


<% @comments.each do |comment| %>
  <%= render 'comment', comment: comment %>
<% end %>