config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  match '/auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  
  get '/home', to: 'static_pages#home', as: :home
  get '/about', to: 'static_pages#about', as: :about
  get '/random', to: 'posts#random', as: :random
  post '/report', to: 'reports#create', as: :report
  get '/admin', to: 'static_pages#admin', as: :admin

  resources :posts do
    member do
      put "like" , to: "posts#upvote"
      put "dislike" , to: "posts#downvote"
      get "comments" , to: "comments#show"
    end
  end

  resources :comments
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]
  resources :users, only: [:show]
  resources :tags, only: [:show]
  
  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  include UrlHelp

  PROVIDERS = %w[vimeo youtube vine instagram twitch gif]

  belongs_to :user
  has_many :reports, as: :reportable
	acts_as_votable
  acts_as_commentable
  acts_as_taggable

	validates :title, presence: true, 
			length: {minimum: 2, maximum: 60}

	validates :video_url, presence: true, uniqueness: true

  validates :provider, inclusion: { in: PROVIDERS,
    message: "This URL is not in our list of accepted domains. Please user the following domains: #{PROVIDERS.map{|p| p.titleize}.join(", ")}" }

  def video_url=(url)
    url = UrlHelp::clean_url(url, get_domain(url))
    set_provider(url)
    super
  end

  def get_domain(url)
    return nil unless url.present?
    url = "gif" if UrlHelp::is_gif?(url)
    url = UrlHelp::cut_before_domain(url)
    domain = url.split(".")[0]
  end 

  def set_provider(url)
    domain = get_domain(url) 
    if PROVIDERS.include? domain
      provider = domain
    else
      provider = nil
    end
    self.provider = provider
  end

	def self.highest_voted
    self.order(:cached_votes_down)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy ]
  before_filter :authenticate_user!, only: [:create, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = grab_correct_post
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def random
    @post = Post.offset(rand(Post.count)).first
    redirect_to comments_post_path(@post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path(sort_by: "added_on"), notice: 'post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

 def upvote
    @post = Post.find (params[:id])
    session[:voting_id] = request.remote_ip
    voter = VotingSession.find_or_create_by(ip: session[:voting_id])
    voter.likes @post
    respond_to do |format|
      format.js
    end
end

def downvote
  @post = Post.find (params[:id])
  session[:voting_id] = request.remote_ip
  voter = VotingSession.find_or_create_by(ip: session[:voting_id])
  voter.dislikes @post
  respond_to do |format|
      format.js
  end
end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :video_url, :tag_list)
    end

    def grab_correct_post
  if params[:sort_by] == "most_popular"
    @most_popular = "sort-active"
    Post.all.order(:cached_votes_score =>:desc).paginate(page: params[:page], per_page: 7)
  else
    @added_on = "sort-active"
    Post.all.order("created_at DESC").paginate(page: params[:page],  per_page: 7)
  end
end
end

app/helpers/posts_helper.rb
module PostsHelper

  def embedded_video(post)
    case post.provider
    # YOUTUBE #
    when "youtube"
      return "<div class='embed-responsive embed-responsive-16by9'>\
              <iframe class='embed-responsive-item' src='https://www.youtube.com/embed/#{post.embed_token}' allowFullScreen='true'>\
              </iframe></div>".html_safe
    # VIMEO #
    when "vimeo"
      return "<div class='embed-responsive embed-responsive-16by9'>\
            <iframe src='//player.vimeo.com/video/#{post.embed_token}' frameborder='0' webkitallowfullscreen mozallowfullscreen allowfullscreen>\
            </iframe></div>".html_safe
    # VINE #
    when "vine"
      return "<div class='embed-responsive embed-responsive-16by9'>\
              <iframe class='vine-embed' src='https://vine.co/v/#{post.embed_token}/embed/simple' width='600' height='600' frameborder='0'>\
              </iframe></div>".html_safe
    # INSTAGRAM #
    when "instagram"
      return "<div class='insta_embed'><iframe src='//instagram.com/p/#{post.embed_token}/embed/' width='612' height='710' frameborder='0' scrolling='no' allowtransparency='true'></iframe></div>".html_safe
      # return "<div class='insta_embed'><iframe class='instagram-media instagram-media-rendered' id='instagram-embed-0' src='//instagram.com/p/#{post.embed_token}/embed/captioned/?v=4' height='400'></iframe></div>".html_safe
      # return "<div id='#{post.embed_token}' class='insta_embed'><script>insta_embed('#{post.embed_token}')</script></div>".html_safe
    when "twitch"
      channel = post.embed_token.split("/v/")[0]
      id = post.embed_token.split("/v/")[1]
      return "<div class='embed-responsive embed-responsive-16by9'>\
              <object data='//www.twitch.tv/swflibs/TwitchPlayer.swf' class='clip_embed_player_flash' type='application/x-shockwave-flash'>\
              <param name='movie' value='//www.twitch.tv/swflibs/TwitchPlayer.swf' />\
              <param name='allowScriptAccess' value='always' />\
              <param name='allowNetworking' value='all' />\
              <param name='allowFullScreen' value='true' />\
              <param name='flashvars' value='channel=#{channel}&amp;auto_play=false&amp;start_volume=25&amp;videoId=v#{id}&amp;auto_play=false&amp;eventsCallback=onPlayerEvent' />\
              </object>\
              </div>".html_safe
    when "gif"
      return "<div class='embed-responsive embed-responsive-16by9'>\
              <div class='gif_img'><img src='#{post.video_url}'></div>\
              </div>".html_safe
      # return "<blockquote class='imgur-embed-pub' lang='en' data-id='#{post.video_url.split('.com')[1]}'><a href='#{post.video_url.split('.gif')[0]}'>View post on imgur.com</a></blockquote><script async src='//s.imgur.com/min/embed.js' charset='utf-8'></script>".html_safe
    else
      return "Error"
    end    
          #<div class="embed-responsive embed-responsive-16by9">
          #
  end
end

app/views/posts/_form.html.erb
<%= form_for @post, class: "post_form" do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <body class="form1">
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control form-control-gray", placeholder: "Having a descriptive title will help get more upvotes." %>
  </div>
  <div class="form-group">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url, class: "form-control form-control-gray ", placeholder: "YouTube, Vimeo, Vine, Instagram and Twitch videos are supported, as well .gif links." %>

    <div id="helpBlock" class="help-block">Having an issue with your link? <b>Click here</b> to see accepted URL formats.</div>
    
    <div id="urlFormattingList" style="display:none;">
      <ul>
        <li><span>YouTube</span> youtube.com/watch?v=1A2b3C</li>
        <li><span>Instagram</span> instagram.com/p/1A2b3C</li>
        <li><span>Vine</span> vine.co/v/1A2b3C</li>
        <li><span>Twitch</span> twitch.tv/somechannel/v/1A2b3C</li>
      </ul>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, 'Tags (comma-seperated)' %>
    <%= f.text_field :tag_list, value: @post.tag_list.join(","), class: "form-control form-control-gray" %>
  </div>
  <div class="form-group">
    <%= f.submit "submit", class: "btn btn-primary" %>
</div>
</body>
<% end %>

app/views/posts/_post.html.erb
<div class="<%= cycle('list_line_odd', 'list_line_even')%> text-center video_display_center">
  <div class="row video-post">
    <div class="col-lg-12">

      <div class="row">
        <div class="text-center">
          <h3><%= post.title %></h3>
          
          <div class="content_header_right">
            <%= render "shared/written_content_header", user: post.user, item: post %>
          </div>
          
        </div>
      </div>

      <%= embedded_video(post) %>


      </div>
  </div>

<div class="post_footer row">

  <div class="btn-group col-md-2 vote_buttons tag_list">
    <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-lg sharp", remote: true do %>
      <span class="badge up-vote-<%=post.id%>"><%= post.get_upvotes.size %></span>
      <span class="glyphicon glyphicon-arrow-up"></span>
    <% end %>

    <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-lg sharp", remote: true do %>
      <span class="badge down-vote-<%=post.id%>"><%= post.get_downvotes.size %></span>
      <span class="glyphicon glyphicon-arrow-down"></span>
    <% end %>
  </div>

  
    <div class="col-md-4 tag_list">
      <ul class="post-options pull-left">
        <li><%= link_to "comments(#{post.comment_threads.count})", comments_post_path(post) %></li>
        <li> | <span class="post_share_buttons" data-url="<%= post_url(post) %>" data-title="<%= post.title %>"> share </span></li>
      </ul>
    </div>


    <div class="col-md-4 pull-right row">
      
      
      <div class="btn-group pull-right" role="group">

      <div class="tag_list col-md-6 <%= !post.tag_list.present? ? 'pull-right': '' %>">
      <% if current_user %>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle sharp" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-menu-hamburger"></span> post options
          <span class="caret"></span></button>
          <ul class="dropdown-menu">

          <li><%=link_to "report post", report_path(report: {reportable_id: post.id, reportable_type: "Post"}), id: "report_#{post.class}_#{post.id}", class: "report_link", remote: true, method: :post %></li>
              <% if current_user and (current_user == post.user ||  current_user.admin?) %>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'edit', edit_post_path(post) %></li>
                <li><%= link_to 'destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <% end %>
          </ul>
        </div>
      <% end %> 
      </div> 


      <% if post.tag_list.present? %>
        <div class="tag_list col-md-6">
        
        <div class="dropdown pull-right">
          <button class="btn btn-default dropdown-toggle sharp tag-dropdown-button" type="button" data-toggle="dropdown">tags
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <% post.tag_list.each do |tag| %>
              <li><%= link_to tag, tag_path(tag) %></li>
            <% end %>
          </ul>
        </div>
        </div>
      <% end %>
    </div>
 
    </div>
 

</div>  

</div>

app/views/posts/downvote.js.erb
$('.up-vote-<%=@post.id%>').html('<%= escape_javascript @post.get_upvotes.size.to_s %>');
$('.down-vote-<%=@post.id%>').html('<%= escape_javascript @post.get_downvotes.size.to_s %>');

app/views/posts/edit.html.erb
<h1>editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<br>
<br>
<header>
<h2> What the internet is watching, sorted by 
<%if @most_popular%>
<h2 class= "mp_color">most popular
	</h2>
	<%end%>
<%if @added_on %> 
<h2 class= "ao_color">newest first
</h2>
<%end%>
</h2>
</header>

<br>
<br>


<div class= "btn-group">
<%= link_to posts_path(sort_by: "most_popular"), class: "btn btn-danger sharp" do %>
<span class="glyphicon glyphicon-star"></span> popular
<% end %>
<%= link_to posts_path(sort_by: "added_on"), class: "btn btn-success" do %>
<span class="glyphicon glyphicon-time"></span> newest
<% end %>
<%= link_to random_path, class: "btn btn-primary sharp" do %> 
 <span class="glyphicon glyphicon-random"></span> random
<% end %>
</div>

<div class="post_list">
  <% @posts.each do |post| %>
    <%= render "post", post: post %>
  <% end %>
</div>

<div class="text-center page_info" >
  <%= page_entries_info @posts, model: 'Post' %>
</div>
    
<div class= "text-center pagination_links" >
<%= will_paginate @posts, renderer: BootstrapPagination::Rails, previous_label: "< prev", next_label: "next >", inner_window: 1, outer_window:0 %>
 </div>

app/views/posts/new.html.erb
<h1>post to votieo</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "post", post: @post %>

<%= link_to 'Back', posts_path %>

| <%= link_to 'Comments', comments_post_path(@post) %>

app/views/posts/upvote.js.erb
$('.up-vote-<%=@post.id%>').html('<%= escape_javascript @post.get_upvotes.size.to_s %>');
$('.down-vote-<%=@post.id%>').html('<%= escape_javascript @post.get_downvotes.size.to_s %>');