config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  match '/auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  
  get '/home', to: 'static_pages#home', as: :home
  get '/about', to: 'static_pages#about', as: :about
  get '/random', to: 'posts#random', as: :random
  post '/report', to: 'reports#create', as: :report
  get '/admin', to: 'static_pages#admin', as: :admin

  resources :posts do
    member do
      put "like" , to: "posts#upvote"
      put "dislike" , to: "posts#downvote"
      get "comments" , to: "comments#show"
    end
  end

  resources :comments
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :messages, only: [:new, :create]
  resources :users, only: [:show]
  resources :tags, only: [:show]
  
  root 'posts#index'
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <h4 class="alert alert-<%= name %> text-center">
    <%= msg %>
  </h4>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
</body>
<a href="https://twitter.com/votieo_" class="twitter-follow-button text-center" data-show-count="false" data-show-screen-name="false">Follow @votieo_</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<div class= "text-center">a DKC production</div>
<div class= "textcenter">votieo © 2016 </div>


<script type="text/javascript">
var clicky_site_ids = clicky_site_ids || [];
clicky_site_ids.push(100883497);
(function() {
  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.src = '//static.getclicky.com/js';
  ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
})();
</script>
<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100883497ns.gif" /></p></noscript>
</body>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse" role= "navigation" style="border-radius:0px;">
  <div class="navbar-inner">
    <div class="container">

      <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
      <link rel="icon" href="/favicon.ico" type="image/x-icon">

      <div class="navbar-header">
      <a href="/">
      <%= image_tag "votieo_logo_small.png"%>
      </a>
        
      </div>
      
        
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav pull-right"> 
          <% if current_user and current_user.admin? %>
            <li><%= link_to "admin panel", admin_path %></li>
          <% end %>
          <li><%= link_to 'post a new video', new_post_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'profile', user_path(current_user) %></li>
            <li><%= link_to inbox_with_notification_number, conversations_path %></li>
            <li><%= link_to 'sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'sign in', new_user_session_path %></li>
            <li><%= link_to 'sign up', new_user_registration_path %></li>
            <li><%= link_to 'about', about_path %></li>
          <% end %>
    
        </ul>
      </nav>
    
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>votieo: what the internet is watching</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :application, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

	<body>
		<%= render 'layouts/header' %>

		<%= render 'layouts/flash_messages' %>

		<div id="content" class="container">
		
			<%= yield %>

		</div>

		<%= render 'layouts/footer' %>

	</body>

</html>